spring:
  application:
    name: microtech

  profiles:
    active: ${ACTIVE_PROFILE}

  jpa:
    open-in-view: false

  logging:
    level:
      org:
        springframework: INFO

server:
  port: 8080

tva:
  value: 20